# Generated by Django 4.0.5 on 2022-06-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
