# Generated by Django 4.1 on 2022-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.DateField()),
                ('available', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
