# Generated by Django 4.1 on 2022-09-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(
                default="Description não disponível para este livro"
            ),
            preserve_default=False,
        ),
    ]
