# Generated by Django 4.1 on 2022-08-30 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanmodel",
            name="return_date",
            field=models.DateField(
                default=datetime.datetime(2022, 9, 1, 19, 12, 12, 684852)
            ),
        ),
        migrations.AlterField(
            model_name="loanmodel",
            name="returned_at",
            field=models.DateField(null=True),
        ),
    ]
