# Generated by Django 4.1 on 2022-08-30 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_alter_loanmodel_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanmodel",
            name="return_date",
            field=models.DateField(
                default=datetime.datetime(2022, 9, 1, 19, 14, 9, 514131)
            ),
        ),
        migrations.AlterField(
            model_name="loanmodel",
            name="returned_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
