# Generated by Django 4.1 on 2022-09-03 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_loan_delete_loanmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="return_date",
            field=models.DateField(default=datetime.date(2022, 9, 13)),
        ),
    ]
